### ISSUE TITLE
GDPR question - personal user data used in aggregate data analytics?

### ISSUE THREAD

**Issue by vlbee** [dwyl/learn-security#34]
Question that came up in conversation related to GDPR - If I use personal user data in anonymised aggregated data analytics and then the user opts-out, does their input into the aggregate analysis need to be removed?

**Comment by nelsonic** [comment]
@vlbee _thank you_ for opening this question. 👍 

Answer: "_it depends_" on the `type` of data stored and how _well_ "anonymised" it is. 

> Recital 26 http://www.privacy-regulation.eu/en/recital-26-GDPR.htm 
"_The principles of data protection should therefore not apply to anonymous information, namely information which does not relate to an identified or identifiable natural person or to personal data rendered anonymous in such a manner that the data subject is not or no longer identifiable._"

So, provided that your application effectively anonymises all personally identifiable information
please see: https://en.wikipedia.org/wiki/Personally_identifiable_information#NIST_definition
removing all names, nicknames/usernames, email, address/places, IP address, phone, national/social security number, gender, date-of-birth, etc.
It will be GDPR-compliant.

_Always_ take the approach of "over anonymising" any data,
because there are "Data Scientists" and "Intelligence Experts" 
who's _job_ it is to "de-anonymise" data see: https://en.wikipedia.org/wiki/De-anonymization
And the algorithms for identifying people through anonymised data will only continue to improve
as machine learning and access to larger datasets become widespread.

**Comment by vlbee** [comment]
Thanks @nelsonic ! 

We might be aggregating some anonymised user data (but not personally identifiable information!) in an upcoming FAC project so this is very helpful!
